### <a name="workflow-now-throws-original-exception-instead-of-nullreferenceexception-in-some-cases"></a><span data-ttu-id="d0e63-101">Flujo de trabajo ahora produce la excepción original en lugar de excepciones NullReferenceException en algunos casos</span><span class="sxs-lookup"><span data-stu-id="d0e63-101">Workflow now throws original exception instead of NullReferenceException in some cases</span></span>

|   |   |
|---|---|
|<span data-ttu-id="d0e63-102">Detalles</span><span class="sxs-lookup"><span data-stu-id="d0e63-102">Details</span></span>|<span data-ttu-id="d0e63-103">En .NET Framework 4.6.2 y versiones anteriores, cuando el método de ejecución de una actividad de flujo de trabajo produce una excepción con un <code>null</code> valor para el <xref:System.Exception.Message> propiedad, el tiempo de ejecución de flujo de trabajo de System.Activities produce una <xref:System.NullReferenceException?displayProperty=name>, máscara el excepción original. En el 4.7 de Framework. NET, se produce la excepción previamente enmascarada.</span><span class="sxs-lookup"><span data-stu-id="d0e63-103">In the .NET Framework 4.6.2 and earlier versions, when the Execute method of a workflow activity throws an exception with a <code>null</code> value for the <xref:System.Exception.Message> property, the System.Activities Workflow runtime throws a <xref:System.NullReferenceException?displayProperty=name>, masking the original exception.In the .NET Framework 4.7, the previously masked exception is thrown.</span></span>|
|<span data-ttu-id="d0e63-104">Sugerencia</span><span class="sxs-lookup"><span data-stu-id="d0e63-104">Suggestion</span></span>|<span data-ttu-id="d0e63-105">Si el código se basa en el control de la <xref:System.NullReferenceException?displayProperty=name>, cámbielo para detectar las excepciones que pueden producirse desde sus actividades personalizadas.</span><span class="sxs-lookup"><span data-stu-id="d0e63-105">If your code relies on handling the <xref:System.NullReferenceException?displayProperty=name>, change it to catch the exceptions that could be thrown from your custom activities.</span></span>|
|<span data-ttu-id="d0e63-106">Ámbito</span><span class="sxs-lookup"><span data-stu-id="d0e63-106">Scope</span></span>|<span data-ttu-id="d0e63-107">Secundaria</span><span class="sxs-lookup"><span data-stu-id="d0e63-107">Minor</span></span>|
|<span data-ttu-id="d0e63-108">Versión</span><span class="sxs-lookup"><span data-stu-id="d0e63-108">Version</span></span>|<span data-ttu-id="d0e63-109">4.7</span><span class="sxs-lookup"><span data-stu-id="d0e63-109">4.7</span></span>|
|<span data-ttu-id="d0e63-110">Tipo</span><span class="sxs-lookup"><span data-stu-id="d0e63-110">Type</span></span>|<span data-ttu-id="d0e63-111">Tiempo de ejecución</span><span class="sxs-lookup"><span data-stu-id="d0e63-111">Runtime</span></span>|
|<span data-ttu-id="d0e63-112">API afectadas</span><span class="sxs-lookup"><span data-stu-id="d0e63-112">Affected APIs</span></span>|<ul><li><xref:System.Activities.CodeActivity.Execute(System.Activities.CodeActivityContext)?displayProperty=nameWithType></li><li><xref:System.Activities.AsyncCodeActivity.BeginExecute(System.Activities.AsyncCodeActivityContext,System.AsyncCallback,System.Object)?displayProperty=nameWithType></li><li><xref:System.Activities.AsyncCodeActivity%601.BeginExecute(System.Activities.AsyncCodeActivityContext,System.AsyncCallback,System.Object)?displayProperty=nameWithType></li><li><xref:System.Activities.WorkflowInvoker.Invoke?displayProperty=nameWithType></li></ul>|

